### ISSUE TITLE
Failed to resolve: com.github.troZee:ViewPager2:v1.0.6

### ISSUE THREAD

**Issue by decin** [troZee/ViewPager2#1]
https://github.com/react-native-community/react-native-viewpager/issues/181

�I also encountered this problem, but the other day was good.
I think https://github.com/troZee/ViewPager2 which is not in jcenter, Causing "implementation 'com.github.troZee:ViewPager2:v1.0.6'" to fail

**Comment by troZee** [comment]
Close due https://github.com/react-native-community/react-native-viewpager/issues/181
