### ISSUE TITLE
React项目使用@react-native-community_viewpager，android报错

### ISSUE THREAD

**Issue by BefightingMan** [troZee/ViewPager2#2]
我按步骤将@react-native-community_viewpager集成到Android项目里面，结果Android项目启动不了了，报错ERROR: Failed to resolve: com.github.troZee:ViewPager2:v1.0.6
Show in Project Structure dialog
Affected Modules: android-@react-native-community_viewpager

**Comment by troZee** [comment]
Could you provide more info ? Please run `npx react-native info` in your project.

**Comment by troZee** [comment]
https://github.com/react-native-community/react-native-viewpager/issues/181
